name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node_version:
          - 16
        architecture:
          - x64
    steps:
      - uses: actions/checkout@v3

      - name: Configure Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
            node-version: ${{ matrix.node-version }}
            architecture: ${{ matrix.architecture }}
            registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

        # Fails the build if the working tree is dirty
        # which happens when you don't update the API docs in line
        # with the tsdoc comments
      - name: Check working tree
        run: test -z "$(git status --porcelain)"

      - name: Lint
        run: npm run lint:ts

      - name: Tests
        run: npm test

